# Generated by Django 4.0.4 on 2022-05-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_golduser_goldweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golduser',
            name='goldWeight',
            field=models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=40),
        ),
    ]
