# Generated by Django 4.0.4 on 2022-05-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_golduser_goldweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='golduser',
            name='accountNumber',
            field=models.CharField(default='27895398743897943438734', max_length=255),
            preserve_default=False,
        ),
    ]
