# Generated by Django 4.0.4 on 2022-05-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_golduser_accountnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golduser',
            name='profile_picture',
        ),
    ]
