# Generated by Django 4.0.4 on 2022-06-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
