# Generated by Django 4.0.4 on 2022-05-25 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalGold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradeStatus', models.CharField(choices=[('BG', 'Bought'), ('SD', 'Sold')], default='BG', max_length=2)),
                ('weight', models.DecimalField(decimal_places=20, max_digits=50)),
                ('dateBought', models.DateTimeField(auto_now_add=True)),
                ('rate', models.DecimalField(decimal_places=20, max_digits=50)),
                ('goldUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dateBought'],
            },
        ),
    ]
