# Generated by Django 4.0.4 on 2022-05-25 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0001_initial'),
    ]

    operations = [
    ]
