# Generated by Django 4.0.4 on 2022-05-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0002_auto_20220525_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalgold',
            name='tradeStatus',
            field=models.CharField(choices=[('BG', 'Bought'), ('SD', 'Sold')], max_length=2),
        ),
    ]
