# Generated by Django 4.0.4 on 2022-05-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0003_alter_digitalgold_tradestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalgold',
            name='transactionId',
            field=models.CharField(default='kfjdkfdjioufeiu_+fdffkdj23948398', max_length=255),
            preserve_default=False,
        ),
    ]
