# Generated by Django 4.0.4 on 2022-05-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold', '0004_digitalgold_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalgold',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
